[package]
name = "geotiff_tiler"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.60", features = ["derive"] }
env_logger = "0.11.9"
gdal = "0.19.0"
image = "0.25"
log = "0.4.29"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
